version: "3"
services:
  postgres-db:
    image: postgres:13.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: mydb
      TZ: "Asia/Tokyo"
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume: ~
